### ISSUE TITLE
Import ogg files from SDChard/HDD

### ISSUE THREAD

**Issue by Meresmata** [geigi/cozy#130]
Hi, I tried to import  some files audio books from SDCard and from the SDD.  Most off my files are reencoded .mp3s with ffmpeg to opus. (file extension either .ogg, or opus). 

I removed the old log file and than started importing the files. The resulting logfile was larger than 50 mb. Github allows only thats why I add the log file [cozy.log.gz](https://github.com/geigi/cozy/files/2457100/cozy.log.gz) ziped.

### System Information
- Operating System: Xubuntu 18.04
- Installation source: flathub
- Version of cozy: 0.6.1

**Comment by Meresmata** [comment]
starting python3 in terminal opens a Python 3.6. repl. 

The command that started cozy is: /usr/bin/python3 /app.bin/com.github.geigy.cozy

**Comment by geigi** [comment]
Thanks for reporting. I need to give this a closer look.

**Comment by geigi** [comment]
I investigated even more and the problem cannot be solved as the media backend I'm using (Gst) cannot handle paths with characters that were in the path of the audio files you provided in the log file. But I added error message handling for this case with the files, that could not be imported due to this issue. The user can then rename the files and the import should work.
