### ISSUE TITLE
Incorrect sorting of book files

### ISSUE THREAD

**Issue by ra3ggi** [geigi/cozy#189]
### Bug/Feature description
Incorrect sorting of book files. 
If there are more than 100 files and they are numbered 001.abc.mp3, 002.bcd.mp3, etc.
### Steps to reproduce
Screenshot in filemanager 

![image](https://user-images.githubusercontent.com/54127155/70386693-e11c0280-19ac-11ea-9699-ba3057bb7729.png)

Screenshot in Cozy
![image](https://user-images.githubusercontent.com/54127155/70386703-ff81fe00-19ac-11ea-9176-084f3c2def1e.png)
 
### System Information
- Operating System: MXLinux 18
- Installation source: flatpak
- Version of cozy: 0.6.9

**Comment by geigi** [comment]
Thanks for reporting. I'm trying to reproduce this issue to create a fix.

**Comment by LukaszGrela** [comment]
It doesnt have to be that many, I have a list of 90 files that are sorted incorectly (or I was thinking it was). It turned out that ID3 tag contained the `title` with a number something like `Wiedzmin, rodz.1` or `Wiedzmin, rozdz. 10` and Cozy seems to be sorting by the title. I've removed title entry and now I see it uses (and displays) file name to sort.

**Comment by geigi** [comment]
@LukaszGrela thanks for this information :) That’s the current behavior. The most preferred ordering is track and disk numbers from the tags, then title followed by file name.

**Comment by LukaszGrela** [comment]
Is there a way to alter the order within the app? something like reordering enabled on the list? Tags are not always available or used correctly e.g. I've seen track as `2/30`, `10/30` this, if not parsed to a number, will end up as 10/10, 2/10. Cozy could also fix track tags by this custom order? :) good job otherwise

**Comment by geigi** [comment]
I'm sorry I totally missed your reply... Currently there is no way to alter the ordering, this has not been build yet. I'm also not really sure how to deal with this issue. Getting into tag manipulation is a whole new level as cozy is currently only doing read-only actions on the files. Maybe I can implement a smarter sort algorithm that is able to correctly sort by numbers. 

But I'm glad you're enjoying cozy :) In the meantime the only thing I can recommend is fixing the tags manually with a tool like easyID3.

**Comment by AMashenkov** [comment]
I've similar issue. 
Book file names are just number in the correct order 001.mp3, 002.mp3, and etc.
However, the titles uses different numbers for chapters and sub-chapter: Roman and Arabic numerals.
This lead to incorrect track order in Cozy.

As a developer, I understand it can be hard to fix sorting for this particular case,
but if it would be possible for a user to choose Title vs Fillename sort order, the workaround will be trivial.

Tag manipulations are a bit tricky for most of non-IT users rather than the file renaming.
So, imho, having a filename sort-order option will lead to a better UX?

**Comment by Meresmata** [comment]
I often have the format "Chapter 001.aax" "Chapter 002.aax". But the way Cozy sorts the file is 1 -> 10 -> 100 -> 11.  

I looked in the metadata (with vlc) of file 9 its: 9 / 171. Seams to be okay
