### ISSUE TITLE
Update of Interface and subsorting of folders in audiobooks

### ISSUE THREAD

**Issue by akshy697** [geigi/cozy#195]
### Bug/Feature description
Hi Team,

Thank you for the first audiobookplayer on Linux, i would like to suggest a few changes wchich would be great.  please find the attached file for the interface look , also woul be great if you could add some more features like subsorting of folders and also showing of the time reqired to complete the audiobook like the one is smart audioplayer app .

hoping for the changes, many thanks

**Comment by geigi** [comment]
Hey,

I'm not sure whether I understand your suggestions.
- Cozy is designed so it doesn't care for for folders, you should rather use tags in your audio files.
- You can see the the time required to complete the audiobook when you enable the setting: "Display the whole book instead of the current chapter" or by clicking on the audiobook which opens an overview for the book.
