### ISSUE TITLE
Auto-rescan the directory for changes

### ISSUE THREAD

**Issue by donadigo** [geigi/cozy#21]
Right now it's kind of unclear of how to load the files from the folder. It should be possible to remove the "Scan directory" from the preferences menu and just listen to changes done to the source folder and reload the library.

**Comment by geigi** [comment]
Auto-rescan is not implemented because the user might have the audio books on a network drive. When the user then is connected e.g. via vpn to the network or has a poor wifi connection the auto rescan might be undesirable (at least it would be for me). I will implement auto-rescan additional to the scan directory as the user will be able to disable it in settings. I will also add more info that the user can import new files via drag & drop. Thanks for all your feedback!
