### ISSUE TITLE
MP3 files not detected as audio files

### ISSUE THREAD

**Issue by mmphego** [geigi/cozy#260]
### Bug/Feature description
![Screenshot from 2020-05-07 07-52-20](https://user-images.githubusercontent.com/7910856/81262174-9b3b9700-903d-11ea-9290-29731f928bf7.png)

### Steps to reproduce
Scan directory 
### System Information
- Operating System: Ubuntu 20.04
- Installation source: flatpak
- Version of cozy: 0.6.16

**Comment by geigi** [comment]
Did you verify that this is an issue with long filenames by renaming them? Most of the time this issue occurs with files that are not correctly detected as audio files.

**Comment by mmphego** [comment]
Mmmhh that's a bit odd, I renamed the files and it seems like Cozy cannot correctly detect as audio files. Any tips or suggestions on how to fix this?

**Comment by geigi** [comment]
This is sadly an issue I couldn’t investigate a lot yet because I don’t have any files that cause this issue... Most of the times tagging and writing the files with a tag program like easytag fixes the issue.

Do you have an mp3 file which is not detected and doesn’t have any copyright on it? That would make it a lot easier to reproduce the issue for me :)

**Comment by dxtr12** [comment]
Convert them to OGG using SoundConveter
Apt-get install soundconverter

**Comment by mmphego** [comment]
Thanks @dxtr12, the thought of converting didn't come to mind.
@geigi thanks, i'll close the issue and mark it as resolved.

**Comment by geigi** [comment]
Cozy 0.7 is out with a completely new importer! This should work with every mp3 file you can play back with any other media player on your system.

**Comment by mmphego** [comment]
Thanks, will check it out.
