### ISSUE TITLE
Remove internal/external drive option and make external drive features available for all drives

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#400]
### Bug description

My audiobooks are stored on an internal secondary drive. Every time I start my PC, I have to manually open this drive in the file manager to mount it.

Sometimes I accidentally open Cozy before I mount the drive, so it detects there's no books available. So I mount the drive, then Cozy scans my library and imports the books.

But once the books are reimported, I lose all my progress and settings for the aduiobooks (such as the playback speed). Cozy should persist this data, without it being lost if something like this happens.

### Steps to reproduce

1. Put audiobooks in a folder somewhere
2. Import the audiobooks in Cozy
3. Play one of the audiobooks. Also change the track speed
4. Close Cozy
5. Move the audiobooks folder somewhere else
6. Open Cozy, your audiobooks should be gone
7. Move the audiobooks folder back to the original location
8. Cozy should reimport the audiobooks
9. Once reimported, play the audiobook from earlier. Your progress and track speed data should be gone

### System Information
- Operating System: Ubuntu 20.04.1 LTS
- Installation source: flatpak
- Version of cozy: 0.7.8

**Comment by geigi** [comment]
Thanks for reporting :) have you marked your storage location as external in the preferences? If you do this Cozy will detect wether a drive is mounted or not.

**Comment by dspacejs** [comment]
@geigi it was marked as an internal drive. Both internal and external drives can be mounted or unmounted, therefore shouldn't Cozy detect if it's mounted in either case? Marking it as external isn't really correct, since it's an internal drive.

**Comment by geigi** [comment]
Yes that's true. I'll make this feature available for all storage locations and remove the internal/external setting to make things more simple. Thanks for the feedback :)

**Comment by artm** [comment]
The terminology is unclear. What is called "external" really means "transient" (will sometimes be missing). 
The distinction is unnecessary though: just expect any location as potentially transient, why should the user care?

**Comment by geigi** [comment]
That's true. My initial thought for this feature was that Cozy is able to detect when a file has moved (on an _internal_ drive) because it then prompts the user to select the new path for the given file. When a drive is _external_ though, this dialog would make no sense because the file is only temporarily not available.

But I also do think that it is way more easy for the user if he doesn't have to make this distinction.

**Comment by dspacejs** [comment]
Additionally, I noticed marking a drive as external causes some UI to show up on audiobooks where the user can download them. This doesn't make sense—how are you supposed to "download" a file internally stored on your PC? And even if you technically could, why would you want it? It'd just duplicate the file.

The only reason I can see this would make sense, is if the audiobook is being streamed from an external server or something (such as what podcast players do).

**Comment by geigi** [comment]
This is the point of this feature :) I'll give you an example.

I store my audiobooks on a network drive and Cozy is running on my laptop. When I'm traveling I want to listen to my books on the go but I don't have access to my network. For that I enable the download switch and I have a local copy to listen to on the go. This is why I created the distinguishing between external and internal in the first place. When I remove the separation the download switch will be visible all the time.

**Comment by geigi** [comment]
Maybe there is a way to detect this in code and display the download button only on external or network drives. This would probably solve the confusion for the users as well.

**Comment by geigi** [comment]
I found a solution to detect drives which are mounted at a later state properly. I'll test it with your situation (secondary internal drive which is mounted manually). But it will probably display the download button in your case because it's not possible to distinguish between actual external drives like usb and network drives and internal drives which are mounted at a later state. At least not with Gio which belongs to the Gnome framework.

There will be still the option to disable the feature if the automatism detects the situation wrongly.

I'll also alter the cleanup so that books which can not be found will not be removed from the library instantly. This should fix your issue :)

**Comment by geigi** [comment]
I've implemented everything as described :) It'll be included in the next release!
