### ISSUE TITLE
[Enhancement] Add spacing between view buttons

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#440]
### Feature description

There is no spacing between these buttons:

![Screenshot from 2021-02-24 12-54-31](https://user-images.githubusercontent.com/9282837/108938201-877e2180-769f-11eb-8746-61bd962dd8c2.png)

### Steps to reproduce

1. Open Cozy
2. There should be no spacing between these buttons

### System Information
- Operating System: Ubuntu 20.04.1 LTS
- Installation source: flatpak
- Version of cozy: 0.8.1

**Comment by geigi** [comment]
This is an issue of the theme (Ubuntu?) you're using. Most themes will display the Switcher correctly like this:

https://puri.sm/wp-content/uploads/2019/06/adaptive-view-switcher-modes-ad.png

In case if Ubuntu it will be fixed with Ubuntu 21.04 :)

I'll close this because it's a theme issue not an issue with cozy.

**Comment by dspacejs** [comment]
@geigi oh, I don't know much about how Linux desktops app work. I just assumed you custom designed this yourself, or it wasn't tweaked properly or something. Are you sure that's a theme issue?

**Comment by geigi** [comment]
Hey no worries :) I'm always trying the most popular themes (adwaida, yaru from Ubuntu and a few others) and this issue only exists on yaru for me. I tried yaru from the GitHub master and it is fixed there :)
