### ISSUE TITLE
Playback speed is reset in-between chapters

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#475]
### Bug description

After the latest update, if you increase the speed of an audiobook, when it plays the next chapter it resets the speed.

### Steps to reproduce

1. Play an audiobook
2. Wait until the next chapter is reached

### System Information
- Operating System: Ubuntu 20.04.2 LTS
- Installation source: flatpak
- Version of cozy: 0.9.4

**Comment by dspacejs** [comment]
@geigi note this also happens when going backwards, i.e if I start a chapter and rewind 30 secs, it'll also reset the speed.

**Comment by dspacejs** [comment]
Also just a dev tip: perhaps consider adding some unit tests? You'd be able to ensure things don't break on new updates. It's well worth the effort and saves time in the long run.

**Comment by geigi** [comment]
Thanks :) Cozy already has ~150 unit tests but some parts regarding the playback are difficult to test because they rely on the gstreamer library which is written in C. Changing the playback speed is not as easy as it might sound like because the interface of gstreamer has its own quirks (e.g. changing the playback speed requires you to execute a jump and appending the playback speed, but this is only possible when the file is loaded 100% and the gstreamer player is in a specific state).

Maybe this can be included in a unit test but I think at least some parts cannot be tested with a simple unit test and require something like an integration test.

**Comment by dspacejs** [comment]
@geigi hmm, it seems like the issue here is likely the command being passed to gstreamer. I doubt gstreamer itself is causing the issue. If you mock the library, you can just test the playback speed that way, simulating switching between chapters and ensuring the speed stays the same.

I haven't got time to review the code, but that's generally how I test these sorts of things.

**Comment by dspacejs** [comment]
@geigi can this please be prioritised over other issues? It's a massive hassle listening to audiobooks now, I have to go and reset it with every new chapter. Thanks.

**Comment by geigi** [comment]
Hey, sorry it is top prio but I had no time to work on cozy yet. Maybe I find some time today but I don't know yet

**Comment by dspacejs** [comment]
@geigi no problem, thanks for the fix

**Comment by dspacejs** [comment]
@geigi is it possible to get this next release with this published soon? I just need that one fix to download. Cheers
