### ISSUE TITLE
m4b books have no name without album tag

### ISSUE THREAD

**Issue by alexminder** [geigi/cozy#536]
### Bug/Feature description
M4B have "Track name" tag, but absent "Album" tag. 
Book name in such case taken from filename. But here incorrect charsets in book name if filename have non ASCII symbols (`Государство.m4b`):

```
$ mediainfo --Output=JSON Государство.m4b | jq -c '.[] | .track|.[0]| .Title, .Album'
"Государство"
null
```

![2021-06-10_12-06-1623319034](https://user-images.githubusercontent.com/15701425/121505487-66cda380-c9d2-11eb-9d67-cd92f0621da4.png)

### Steps to reproduce
- Prepare M4B book with Title tag filled and absent Album tag.
- Add the book to cozy library

### System Information
- Operating System: Linux
- Installation source: distr package
- Version of cozy: 1.0.2

**Comment by geigi** [comment]
Since version v1.0.3 your issue should be resolved because file and folder names are now properly decoded. To update your book in Cozy's library you'll either have to remove and add your file again or change the modification timestamp of the file. E.g. like this:
```
touch $your_file.m4b
```

A small info: In case of the book name the fallback is actually the directory name which contains the audiobook file(s). The filename is used for the chapter name :)
