### ISSUE TITLE
Compressed File Support

### ISSUE THREAD

**Issue by trymeouteh** [geigi/cozy#541]
Please add support for compressed files such as 7Z files. This way users can take all the MP3 files of an audiobook and place them inside of a compressed 7Z file and have only one file to manage an entire audiobook and have it take up less storage space.

- Compressed file make the audiobook file smaller in size
- Easy to edit (Extract archive, edit file with tag editor, recompress)
- Can take MP3 files and wrapped them into one file (Easier to do than converting MP3 files into an M4B)

This will be easier to manage. M4B look great but there very few programs out there that allow us to edit M4B file for its chapters and tags, making it hard to have an organised audiobook library.

**Comment by geigi** [comment]
Thanks for your feature request :)
I'm sorry but I don't really see a use case for this in Cozy because:
- Compressed audio files like mp3 can't be compressed any more by 7z, there is almost no space gain
- I actually think it is far more complicated to edit because you first have to extract and later on compress again
- I don't see an advantage to having only one file instead of a few.
Still thanks for contributing and I hope you'll enjoy Cozy anyway :)
