### ISSUE TITLE
Add your stripe key to appdata

### ISSUE THREAD

**Issue by danrabbit** [geigi/cozy#551]
In the new version of AppCenter Dashboard, we're no longer modifying your appdata before publishing, so you'll need to add your stripe key to appdata.xml to continue to monetize your app in elementary OS 6

For your convenience, your public stripe key is:
`<value key="x-appcenter-stripe">pk_live_XJocNlICBfLqHpdZXN0LxlyV00xrhZTbDe</value>`

**Comment by geigi** [comment]
Thanks! :) Looking forward to the new AppCenter powered by flatpak :)

**Comment by apandada1** [comment]
@geigi The latest version of the app is still not on AppCenter. https://appcenter.elementary.io/com.github.geigi.cozy/

**Comment by geigi** [comment]
@apandada1 I believe it's currently not possible to publish because Cozy isn't using the `io.elementary.Platform ` base in the flatpak manifest file. I'm currently not sure how to solve this issue. In Cozy's case it would be cool to provide the packaging in a separate repository similar to Flathub packaging. But if I understand correctly only Apps using the elementary platform will be permitted in AppCenter.

**Comment by apandada1** [comment]
I don't know if the following is possible.
Maybe create a different manifest file for AppCenter and create a separate GitHub action for it. It would be nice to have Cozy in the AppCenter.

**Comment by geigi** [comment]
Publishing using a GitHub action is not possible because elementaryOS has it's own pipeline which can't be triggered from the outside as far as I know. It seems like the App Center observes the GitHub repository and pulls everything from within it. Let's move the discussion to #636 :)
