### ISSUE TITLE
.odm file support

### ISSUE THREAD

**Issue by CoderThomasB** [geigi/cozy#664]
Cozy doesn't currently look like it supports the .odm file. This feature would be really helpful when listening to audiobooks from a library.
 
There appears to already be a project that downloads the mp3 data from the cloud using the data from the odm file:
 [https://github.com/chbrown/overdrive](https://github.com/chbrown/overdrive)

**Comment by geigi** [comment]
Hey, thanks for your suggestion!

This feature is out of scope for Cozy though. Cozy follows the principle to be as simple as possible and to do only a limited set of things but do them (hopefully) properly. Therefor supporting specific content providers won't be implemented.

Overdrive seems like a cool project. Because the tool you mentioned already downloads mp3 files, it's very easy to import them into Cozy after downloading.

**Comment by CoderThomasB** [comment]
Lots of libraries use this format so I think it would be confusing to a new user that will just try dragging and dropping with the file transferring but nothing happening. Also if you are worried of it making the project too complicated, then could support for an existing tool be implemented. So Cozy talks to the tool and then it doesn't complicate Cozy’s code any further.

**Comment by geigi** [comment]
Adding a dependency to an already existing tool does also raise Cozy's complexity and sources of error:
- The API of dependencies can change and Cozy must adopt to those changes
- The dependency must be available as a package on all linux distributions where Cozy is packaged for
- Possibly different versions on different distributions must be taken into consideration (maybe the interface or the functionality changed)

I've already experienced all of those issues with dependencies currently used by Cozy. I only have limited time to work on Cozy and therefor I think, from the projects standpoint, it's not a good idea to build support for this, sorry...

Because Cozy doesn't advertise support for odm files, libraries or other content providers I believe that most people also don't expect Cozy to support this functionality.

**Comment by geigi** [comment]
I've given this more thought and maybe what Cozy needs is something like a plugin system. I can think of at least one other feature request (support for booksonic servers) which would also profit from this. This would separate support for additional content providers from Cozy's codebase. I think contributors would also benefit from this because they can start write a plugin and don't have to delve deep into Cozy's codebase.

**Comment by CoderThomasB** [comment]
> I've given this more thought and maybe what Cozy needs is something like a plugin system. I can think of at least one other feature request (support for booksonic servers) which would also profit from this. This would separate support for additional content providers from Cozy's codebase. I think contributors would also benefit from this because they can start write a plugin and don't have to delve deep into Cozy's codebase.

I really like that Idea! there is already a plugin system for geary that could be used as a reference to create this one!

**Comment by geigi** [comment]
I've created a new issue to discuss this #665 

Also I want to give proper credit: thanks @paulschwoerer for introducing the idea of a plugin system ;)
