### ISSUE TITLE
Add zip support

### ISSUE THREAD

**Issue by makaleks** [geigi/cozy#668]
### Feature description

What do you think about `zip` support when loading books? In general archives are simpler for transfer and integrity check, they allow to store an audiobook or a finished book series as a single entity. Zip is the most widespread format and very common for text ebooks. A single book is rarely updated, there is no need to store its peaces separately on a filesystem. 

### Steps to reproduce

- Open cozy
- Select directory with zip-books
- Find nothing imported (currently)

### System Information
- Operating System: Arch, Gnome
- Installation source: Flatpak
- Version of cozy: 1.1.2

**Comment by geigi** [comment]
Thanks for your request :) 
The feature you've been thinking about is mostly also available as a standard: `m4b` files. It's a single audio file containing chapters and is specifically designed for audio books. A single `m4b` file contains a whole book. Therefor also solves the problems of being simple to transfer and integrity check. I suggest that you convert your audio books to m4b to gain all those features.

Supporting zip files is out of scope for Cozy because the m4b standard exists which solves very similar problems.

You could try this tool to convert your files. I haven't tried it myself but it looks useful:
https://github.com/yermak/AudioBookConverter

For reference: there has been a similar request in the past: #541
