### ISSUE TITLE
Scanning (large-ish) Library freezes PC

### ISSUE THREAD

**Issue by ReaderGuy42** [geigi/cozy#702]
### Bug/Feature description
I now have all my books tagged with cover images, and authors using EasyTag as you suggested. However, now when I go back to Cozy and have it scan the library it freezes my PC after a few minutes. I can't be 100% sure it's Cozy since I was also doing other stuff, but it's happened three times within 24 hours and each time I was trying to have Cozy scan in the background. And my PC doesn't usually freeze like this, so I'm pretty sure it's Cozy.

### Steps to reproduce
1. Have large library
2. Scan library
3. freeze
4. have to hard reset PC

### System Information
- Operating System: Linux Mint 20.3
- Installation source: flatpak
- Version of cozy: 1.2.0

Any ideas?
Thanks :)

**Comment by geigi** [comment]
Hi,
Hm have no idea. I also have quite a large library and this never happened to me. Cozy also runs on low end machines like a raspberry pi or on phones without freezing the whole system. And even a raspberry pi can handle thousands of files when scanning. 

You can have a look at Cozy's log file after a crash:

```
~/.var/app/com.github.geigi.cozy/data/cozy/cozy.log
```

I dont know what you use your computer for but as scanning is a memory, disk and also a bit cpu intensive, there might still be something wrong with your system which is not triggered when it is mostly doing nothing. 

It would also be very unlikely for a GTK application to freeze the whole system due to a bug in the app. I have no idea how this could be even achieved 😅

**Comment by geigi** [comment]
Also you could have a look at ```
/var/log/syslog
```
for the last messages before the crash

**Comment by ReaderGuy42** [comment]
Ok, I looked at the logs, but cozy.log was empty and I coudn't find anything in syslog. You're right, it's likely something else, as it just happened again but with EasyTag. Thanks though.
