### ISSUE TITLE
Issue with removing audiobook from library

### ISSUE THREAD

**Issue by peter099** [geigi/cozy#718]
### Bug/Feature description

If i want to remove audiobook from the library without deleting it from my hard disk, it doesn't seem there is such a option. It removes the audiobook from library but also deletes it from the hard disk.

### Steps to reproduce

Right click on audiobook cover and select 'Remove from library'. It ask me to delete the audiobook from hard disk.

### System Information

- Operating System: MX Linux
- Installation source: flatpak
- Version of cozy: 1.2.0

**Comment by geigi** [comment]
Hey, thanks for reporting. This is a design I made because it gets quite complex if you change this behavior. Cozy imports all books in the selected directories. If you allow removing a book from the library without deleting it from the disk, it would get reimported on the next import.

If you don't want to include certain files, move them to a directory which is not added to cozy. After that you can remove the books from the library. You won't see the dialog to delete files then.

**Comment by geigi** [comment]
Im sorry about that... that's why there is the explicit warning that the files will be deleted from the disk. Removing from the library doesn't make any sense though as they will be added again at the next scan.
